// <auto-generated />
using System;
using BikeBuilderAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeBuilderAPI.Migrations
{
    [DbContext(typeof(AccountsContext))]
    [Migration("20250615075633_SavedBikeTable")]
    partial class SavedBikeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BikeBuilderAPI.Model.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BikeBuilderAPI.Models.SavedBike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bars")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BikeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Drivetrain")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fork")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pedals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Saddle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seatpost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shock")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Stem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tyres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Wheels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SavedBikes");
                });

            modelBuilder.Entity("BikeBuilderAPI.Models.SavedBike", b =>
                {
                    b.HasOne("BikeBuilderAPI.Model.Account", "Account")
                        .WithMany("SavedBikes")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BikeBuilderAPI.Model.Account", b =>
                {
                    b.Navigation("SavedBikes");
                });
#pragma warning restore 612, 618
        }
    }
}
